#!/bin/bash
docker compose down

php_service=$(grep PHP_SERVICE .env | cut -d '=' -f2)
db_version=$(grep VERSION_MYSQL .env | cut -d '=' -f2)
web_service=$(grep WEB_SERVICE .env | cut -d '=' -f2)

docker rmi microservicios-$php_service microservicios-$web_service mysql:$db_version

if [ -d "./src/" ];
then
  rm -rf "./src"
fi

