#!/bin/bash
# VARIABLES
db_passwd=$(grep DB_PASSWD .env | cut -d '=' -f2)
db_service=$(grep DB_SERVICE .env | cut -d '=' -f2)
db_user=$(grep DB_USER .env |cut -d '=' -f2)
db_name=$(grep DB_NAME .env | cut -d '=' -f2)
php_service=$(grep PHP_SERVICE .env | cut -d '=' -f2)
dir_share=$(grep DIR_SHARE .env | cut -d '=' -f2)
dir_apache=$(grep DIR_APACHE .env | cut -d '=' -f2)
dir_templates=$(grep DIR_TEMPLATES .env | cut -d '=' -f2)

# CREATE FOLDERS IF NOT EXISTS
if [ ! -d $dir_share ]; then
  mkdir $dir_share
fi

if [ ! -d $dir_apache ]; then
  mkdir $dir_apache
fi

# COPY TEMPLATE
cp $dir_templates/template_index temp

# REPLACE
sed -i "s/DB_PASSWD/$db_passwd/g" temp
sed -i "s/DB_SERVICE/$db_service/g" temp
sed -i "s/DB_USER/$db_user/g" temp
sed -i "s/DB_NAME/$db_name/g" temp

# SEND INDEX.PHP TO PUBLIC_HTML
mv temp  $dir_share/index.php

# PHP URL IN APACHE DOCKERFILE MODIFICATION
cp $dir_templates/template_apache temp
sed -i "s/PHP_SERVICE/$php_service/g" temp
mv temp  $dir_apache/Dockerfile

# DOCKER COMPOSE UP
docker compose up
